DROP TABLE IF EXISTS panthers_offense_log;
DROP TABLE IF EXISTS panthers_defense_log;
DROP TABLE IF EXISTS panthers_team_stats;
DROP TABLE IF EXISTS falcons_offense_log;
DROP TABLE IF EXISTS falcons_defense_log;
DROP TABLE IF EXISTS falcons_team_stats;
DROP TABLE IF EXISTS saints_offense_log;
DROP TABLE IF EXISTS saints_defense_log;
DROP TABLE IF EXISTS saints_team_stats;
DROP TABLE IF EXISTS bucs_offense_log;
DROP TABLE IF EXISTS bucs_defense_log;
DROP TABLE IF EXISTS bucs_team_stats;

CREATE TABLE panthers_offense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE panthers_defense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE panthers_team_stats (
    Team TEXT,
    pts_scored INT,
    tot_yds INT,
    tot_plys INT,
    yds_per_ply DECIMAL(5,2),
    tov INT,
    fmbl INT,
    frst_downs INT,
    tot_comp INT,
    tot_pass_att INT,
    pass_yds INT,
    pass_td INT,
    ints INT,
    net_yds_per_att DECIMAL(5,2),
    pass_frst_downs INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    rush_frst_downs INT,
    pen INT,
    pen_yds INT,
    pen_frst_downs INT,
    tot_drives INT,
    score_perc DECIMAL(5,2),
    tov_perc DECIMAL(5,2),
    avg_strt_line DECIMAL(5,2),
    time_per_drv TIME,
    plys_per_drv DECIMAL(5,2),
    yds_per_drv DECIMAL(5,2),
    pts_per_drv DECIMAL(5,2)
);

CREATE TABLE falcons_offense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE falcons_defense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE falcons_team_stats (
    Team TEXT,
    pts_scored INT,
    tot_yds INT,
    tot_plys INT,
    yds_per_ply DECIMAL(5,2),
    tov INT,
    fmbl INT,
    frst_downs INT,
    tot_comp INT,
    tot_pass_att INT,
    pass_yds INT,
    pass_td INT,
    ints INT,
    net_yds_per_att DECIMAL(5,2),
    pass_frst_downs INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    rush_frst_downs INT,
    pen INT,
    pen_yds INT,
    pen_frst_downs INT,
    tot_drives INT,
    score_perc DECIMAL(5,2),
    tov_perc DECIMAL(5,2),
    avg_strt_line DECIMAL(5,2),
    time_per_drv TIME,
    plys_per_drv DECIMAL(5,2),
    yds_per_drv DECIMAL(5,2),
    pts_per_drv DECIMAL(5,2)
);

CREATE TABLE saints_offense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE saints_defense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE saints_team_stats (
    Team TEXT,
    pts_scored INT,
    tot_yds INT,
    tot_plys INT,
    yds_per_ply DECIMAL(5,2),
    tov INT,
    fmbl INT,
    frst_downs INT,
    tot_comp INT,
    tot_pass_att INT,
    pass_yds INT,
    pass_td INT,
    ints INT,
    net_yds_per_att DECIMAL(5,2),
    pass_frst_downs INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    rush_frst_downs INT,
    pen INT,
    pen_yds INT,
    pen_frst_downs INT,
    tot_drives INT,
    score_perc DECIMAL(5,2),
    tov_perc DECIMAL(5,2),
    avg_strt_line DECIMAL(5,2),
    time_per_drv TIME,
    plys_per_drv DECIMAL(5,2),
    yds_per_drv DECIMAL(5,2),
    pts_per_drv DECIMAL(5,2)
);

CREATE TABLE bucs_offense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE bucs_defense_log (
    Rk INT,
    Gtm INT,
    week INT,
    date DATE,
    day TEXT,
    loc TEXT,
    opp TEXT,
    result TEXT,
    pts INT,
    ptsa INT,
    ot TEXT,
    pass_cmp DECIMAL(5,2),
    pass_att INT,
    comp_perc DECIMAL(5,2),
    pass_yds INT,
    pass_td INT,
    pass_yds_per_att DECIMAL(5,2),
    adj_yds_per_att DECIMAL(5,2),
    qb_rating DECIMAL(5,2),
    sacks_all INT,
    yds_lost_sack INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    total_plays INT,
    total_yds INT,
    yds_per_play DECIMAL(5,2),
    fga INT,
    fgm INT,
    xpa INT,
    xpm INT,
    pnt INT,
    punt_yds INT,
    frst_down_by_pass INT,
    frst_down_by_rush INT,
    frst_down_by_pen INT,
    frst_downs INT,
    thrd_down_conv INT,
    thrd_down_att INT,
    frth_down_conv INT,
    frth_down_att INT,
    penalties INT,
    pen_yds INT,
    fumb_lost INT,
    ints INT,
    turnovers INT,
    time_of_poss TIME,
    game_id INTEGER PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE bucs_team_stats (
    Team TEXT,
    pts_scored INT,
    tot_yds INT,
    tot_plys INT,
    yds_per_ply DECIMAL(5,2),
    tov INT,
    fmbl INT,
    frst_downs INT,
    tot_comp INT,
    tot_pass_att INT,
    pass_yds INT,
    pass_td INT,
    ints INT,
    net_yds_per_att DECIMAL(5,2),
    pass_frst_downs INT,
    rush_att INT,
    rush_yds INT,
    rush_td INT,
    rush_yds_att DECIMAL(5,2),
    rush_frst_downs INT,
    pen INT,
    pen_yds INT,
    pen_frst_downs INT,
    tot_drives INT,
    score_perc DECIMAL(5,2),
    tov_perc DECIMAL(5,2),
    avg_strt_line DECIMAL(5,2),
    time_per_drv TIME,
    plys_per_drv DECIMAL(5,2),
    yds_per_drv DECIMAL(5,2),
    pts_per_drv DECIMAL(5,2)
);